### PR TITLE
Responsive

### PR DESCRIPTION
**Pull request by frankylee**
We still need to adjust font-families and tweak the design, but I removed tons of unused code and cleaned up redundancies. I also added media queries to appropriate break-points and made some adjustments for the responsive design and mobile-view. Hopefully this is more organized and easier to read for ya'll as well.

### CODE REVIEW

**Comment by EmmaDawsonDev** [comment]
Hi Frankylee! It's looking really good so far, I just have a few small things I noticed that don't quite work right yet:

1. At less than 400px the h1 is too big and disappearing off the page.
2. Between 400px and 768px the h1 is too small, it needs to be bigger than the p text under it (the p text could probably also be a little smaller, it's a little too big to read comfortably at the moment).
3. When the logo is hidden (< 576px) the h1 needs to left align with the rest of the text.
4. When the black overlay is 100% width the CTA link (pink button) would probably look better center aligned or left aligned with the rest of the text
5. There is some slight overlap and cramping of the CTA link/button and the last line of text between 768px - 1040px (ipad and ipad pro sizes). Maybe the button should be moved down to avoid issues when the text breaks in different places?

**Comment by EmmaDawsonDev** [comment]
If you don't want to do the changes yourself then I think what you've done so far is totally ok to merge and then someone else can carry on and do the suggestions. So you can chose what works best for you :)

**Comment by frankylee** [comment]
> 1. At less than 400px the h1 is too big and disappearing off the page.
> 2. Between 400px and 768px the h1 is too small, it needs to be bigger than the p text under it (the p text could probably also be a little smaller, it's a little too big to read comfortably at the moment).
> 3. When the logo is hidden (< 576px) the h1 needs to left align with the rest of the text.
> 4. When the black overlay is 100% width the CTA link (pink button) would probably look better center aligned or left aligned with the rest of the text
> 5. There is some slight overlap and cramping of the CTA link/button and the last line of text between 768px - 1040px (ipad and ipad pro sizes). Maybe the button should be moved down to avoid issues when the text breaks in different places?


Squashed these bugs.

**Comment by EmmaDawsonDev** [comment]
Looks fantastic! Great job :D

**Comment by communitybuildingcoders** [comment]
All the changes look great! Merging to master.

**Pull request merged**
